title: "Practice"
date: 2020-12-29
author: AbKumar
email:- abkumar@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  
  
  "This task is only for practicing purpose. Only seeing how this task will be performed."

# social links
twitter_username: abkumar9677 # DO NOT include the @ character, or else the build will fail!
github_username:  abkumar9677 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
